# Generated by Django 2.2 on 2020-09-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
